### ISSUE TITLE
Add the discord link in readme.md

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/YouTube-Thumbnail-Downloader#4]
There should be a discord link in the readme.md file to discord.semikolan.co with a little description that says "You can join the Semikolan Discord Server to have a discussion about the project or ask out about any other queries." or anything similar.
It would be great if you add some content mentioning the need for joining the server
Like we can mention something like, If you want to Communicate with the Other Contributors on this Project, then do join https://discord.semikolan.co

**Comment by darshilagrawal** [comment]
Can you assign this to me ?

**Comment by neodark** [comment]
Can I work on this one too please?

**Comment by ankurg132** [comment]
@darshilagrawal you can go for it. @neodark let's give this one to @darshilagrawal first!

**Comment by neodark** [comment]
sure! :+1:

**Comment by darshilagrawal** [comment]
The changes have been made @ankurg132 do let me know in case of any discrepancies
